@startuml server_activity_clients
start
:Адміністратор відкриває панель керування;
:Додавання/редагування/видалення клієнтів;
:Оновлення даних у БД;
:Формування актуального списку;
stop
@enduml
