@startuml server_activity_booking
start
:Отримати запит від клієнта;
:Перевірити доступність майстра;
if (Майстер доступний?) then (Так)
  :Зберегти запис у БД;
  :Надіслати підтвердження клієнту;
else (Ні)
  :Надіслати відмову клієнту;
endif
stop
@enduml
