@startuml client_activity_edit_cancel
start
:Вхід у систему;
:Перегляд своїх записів;
if (Вибір дії) then (Редагування)
  :Вибір нового часу;
  :Підтвердження змін;
else (Скасування)
  :Підтвердження скасування;
endif
stop
@enduml
